import { Cabin_Sketch } from "next/font/google";
import "./globals.css";

const cabinSketch = Cabin_Sketch({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabinSketch.className}>{children}</body>
    </html>
  );
}
